# Generated by Django 4.2.17 on 2025-01-06 21:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_status_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code.', max_length=128, region=None),
        ),
    ]
