# Generated by Django 4.2.17 on 2025-01-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Stock_Quantity',
            new_name='stock_Quantity',
        ),
    ]
