# Generated by Django 4.2.17 on 2025-01-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_stock_quantity_product_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_Quantity',
            new_name='stock_quantity',
        ),
    ]
